### PR TITLE
add deserialize function to JWTPayload

### PR DESCRIPTION
**Pull request by 0xpr03**
Attempt at implementing #8

### CODE REVIEW

**Comment by hidekatsu-izuno** [comment]
Could you please tell me the intention of this pull request?
I don't think this feature is nessecity.

**Comment by 0xpr03** [comment]
It allows deserializing the JWT payload into a pre-defined structure via serde.
This way you can automatically get a struct of all the claims you require and get a verification of the types in one go.

This is very similar to what you can do in jsonwebtoken [here](https://github.com/Keats/jsonwebtoken/blob/2f25cbed0a906e091a278c10eeb6cc1cf30dc24a/examples/validation.rs#L22) after defining your structure above (line 5-10).

**Comment by 0xpr03** [comment]
If you don't think its useful you can close it.

**Comment by hidekatsu-izuno** [comment]
I'm sorry, but since I've closed the issue #8, I am going to close this pull request as well.

**Pull request closed without merging**
